language: node_js
node_js:
  - "12.17.0"
addons:
  chrome: stable

cache:
  directories:
    - node_modules
branches:
  only:
  - master

install:
  - npm install  

before_script:
  - npm install -g @angular/cli
script:
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm run build